name: Release VSCode Extension

on:
  push:
    tags:
      - 'v1.0.4'

permissions:
  contents: write 
   
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run compile

      - name: Package VSCode extension (.vsix)
        run: vsce package

      - name: Create source archive
        run: zip -r source-code.zip ./src ./package.json ./README.md .github

      - name: Find generated VSIX file
        id: find_vsix
        run: echo "::set-output name=vsixfile::$(ls *.vsix)"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload VSIX to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_vsix.outputs.vsixfile }}
          asset_name: ${{ steps.find_vsix.outputs.vsixfile }}
          asset_content_type: application/octet-stream

      - name: Upload source archive to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source-code.zip
          asset_name: source-code-${{ github.ref_name }}.zip
          asset_content_type: application/zip
